package com.example.praktikum_4;

import java.util.ArrayList;
import java.util.List;

public class BookData {
    public static List<Book> books = new ArrayList<>();
    public static List<Book> favoriteBooks = new ArrayList<>();

    public static void addToFavorites(Book book) {
        if (!favoriteBooks.contains(book)) {
            favoriteBooks.add(book);
            book.isLiked = true;
        }
    }

    static {
        books.add(new Book("Bumi", "Tere Liye", "2016", "Namaku Raib, usiaku 15 tahun, kelas sepuluh. Aku anak perempuan seperti kalian, adik-adik kalian, tetangga kalian. Aku punya dua kucing, namanya si Putih dan si Hitam. Mama dan papaku menyenangkan. Guru-guru di sekolahku seru. Teman-temanku baik dan kompak.\n" +
                "\n" + "Aku sama seperti remaja kebanyakan, kecuali satu hal. Sesuatu yang kusimpan sendiri sejak kecil. Sesuatu yang menakjubkan.\n" +
                "\n" + "Namaku Raib. Dan aku bisa menghilang.", R.drawable.cover1, false));
        books.add(new Book("Hello", "Tere Liye", "2023", "KISAH DISAH ini sudah tertinggal puluhan tahun lebih. Maka ibarat seseorang yang ketinggalan kereta, bukan cuma kilau lampu dan getar rel yang telah hilang di tikungan sana, bahkan gerbong dan lokomotifnya sudah karatan dipensiunkan.\n" +
                "\n" + "Cerita ini sudah menguap puluhan tahun lebih. Maka ibarat embun menggelayut malas di daun rumput, rerumputan itu sudah menjadi hutan, tidak tersisa lagi kenangannya.\n" +
                "\n" + "Tetapi tak mengapa. Meskipun sudah tertinggal jauh, boleh jadi cerita ini menyenangkan untuk dibaca.", R.drawable.cover2, false));
        books.add(new Book("Laut Bercerita", "Leila Salikha Chudori", "2017", "Di sebuah senja, di sebuah rumah susun di Jakarta, mahasiswa bernama Biru Laut disergap empat lelaki tak dikenal. Bersama kawan-kawannya, Daniel Tumbuan, Sunu Dyantoro, Alex Perazon, dia dibawa ke sebuah tempat yang tak dikenal. " +
                "Berbulan-bulan mereka disekap, diinterogasi, dipukul, ditendang, digantung, dan disetrum agar bersedia menjawab satu pertanyaan penting: siapakah yang berdiri di balik gerakan aktivis dan mahasiswa saat itu.", R.drawable.cover3, false));
        books.add(new Book("Perpustakaan Tengah Malam", "Matt Haig", "2020", "Di antara kehidupan dan kematian terdapat sebuah perpustakaan yang jumlah bukunya tak terhingga. Tiap—tiap buku menyediakan satu kesempatan untuk mencoba kehidupan lain yang bisa dijalani sehingga kau bisa melihat apa yang terjadi kalau kau mengambil keputusan—keputusan berbeda…\n" +
                "\n" + "Akankah kau melakukan apa pun secara berbeda jika kau mendapat kesempatan untuk membatalkan penyesalan–penyesalanmu? Benarkah kehidupan lain akan jauh lebih baik? Nora Seed harus membuat keputusan. Ia dihadapkan pada kemungkinan bisa mengubah hidupnya, memiliki karier yang berbeda, tidak putus dari mantan kekasih, mewujudkan mimpinya sebagai glasiolog.", R.drawable.cover4, false));
        books.add(new Book("Kita Pergi Hari Ini", "Ziggy Zezsyazeoviennazabrizkie", "2021", "Mi dan Ma dan Mo tidak pernah melihat kucing seperti Nona Gigi. Tentu saja, mereka sudah pernah melihat kucing biasa. Tapi Nona Gigi adalah Kucing Luar Biasa. Kucing Luar Biasa berarti kucing yang di luar kebiasaan. Nona Gigi adalah Cara Lain yang dinantikan oleh Bapak dan Ibu Mo untuk menjaga Mi, Ma, dan Mo ketika keduanya keluar rumah mencari uang. Sebab di Kota Suara, semua uang yang tersedia di dasar laut sudah diambil oleh para perompak, uang di bawah tanah diambil oleh para perampok, dan uang di ranting pohon diambil oleh pengusaha kayu yang jahat.\n" +
                "\n" + "Nona Gigi mengajak Mi dan Ma dan Mo dan Fifi dan Fufu—anak kembar Tetangga Baru bertualang mengunjungi tempat-tempat indah. Mereka naik Kereta Air, bertemu Kolonel Jagung, bermain di Sirkus Sendu, dan menyaksikan kemegahan Kota Terapung Kucing Luar Biasa.", R.drawable.cover5, false));
        books.add(new Book("Fourth Wing", "Rebecca Yaros", "2025", "Awalnya, Violet Sorrengail dipersiapkan untuk memasuki Kuadran Panitera, tempat dia bisa hidup damai dikelilingi buku dan sejarah. Akan tetapi, ibu Violet, Jenderal Lilith Sorrengail, memerintahkan putri bungsunya itu untuk bergabung dengan ratusan kandidat untuk menjadi pasukan elite Navarre, yakni para penunggang naga. Begitu disahkan menjadi kandidat, banyak tantangan menanti Violet. Tubuhnya yang \"lemah\" adalah alasan dia sering dipandang sebelah mata oleh kandidat lain, belum lagi naga pun enggan terikat dengan mereka yang \"lemah\". Jumlah naga dan kandidat yang tidak sebanding juga menjadikan Violet yang-paling-ditargetkan-untuk-mati.", R.drawable.cover6, false));
        books.add(new Book("Cecilia and the Angel", "Jostein Gaarder", "2025", "Pernahkah Anda terpikir betapa menariknya dunia yang terbuka lebar lewat lembaran buku? Membaca bukan hanya kegiatan rutin, tetapi juga petualangan tak terbatas ke dalam imajinasi dan pengetahuan. Membaca mengasah pikiran, membuka wawasan, dan memperkaya kosakata. Ini adalah pintu menuju dunia di luar kita yang tak terbatas. Tetapkan waktu khusus untuk membaca setiap hari.\n" +
                "\n" + "Dari membaca sebelum tidur hingga menyempatkan waktu di pagi hari, kebiasaan membaca dapat dibentuk dengan konsistensi. Pilih buku sesuai minat dan level literasi. Mulailah dengan buku yang sesuai dengan keinginan dan kemampuan membaca. Temukan tempat yang tenang dan nyaman untuk membaca. Lampu yang cukup, kursi yang nyaman, dan sedikit musik pelataran bisa menciptakan pengalaman membaca yang lebih baik. Bergabunglah dalam kelompok membaca atau forum literasi. Diskusikan buku yang Anda baca dan dapatkan rekomendasi dari sesama pembaca. Buat catatan atau jurnal tentang buku yang telah Anda baca.", R.drawable.cover7, false));
        books.add(new Book("Seporsi Mie Ayam Sebelum Mati", "Brian Khrisna", "2025", "Ale, seorang pria berusia 37 tahun memiliki tinggi badan 189 cm dan berat 138 kg. Badannya bongsor, berkulit hitam, dan memiliki masalah dengan bau badan. Sejak kecil, Ale hidup di lingkungan keluarga yang tidak mendukungnya. Ia tak memiliki teman dekat dan menjadi korban perundungan di sekolahnya.\n" +
                "Ale didiagnosis psikiaternya mengalami depresi akut. Bukannya Ale tidak peduli untuk memperbaiki dirinya sendiri, ia peduli. Ale telah berusaha mengatasi masalah-masalah yang timbul dari dirinya agar ia diterima di lingkungan pertemanan. Namun usahanya tidak pernah berhasil. Bahkan keluarganya pun tidak mendukungnya saat Ale membutuhkan sandaran dan dukungan.", R.drawable.cover8, false));
        books.add(new Book("Jakarta Sebelum Pagi", "Ziggy Zezsyazeoviennazabrizkie", "2025", "MESKIPUN ada mayat di dalam lubang kubur, tetap sulit menentukan siapa yang baru saja mati. Nin yang bilang begitu, begitu kami masuk ke dalam mobil. Katanya, orang lewat bisa berpikir kalau kami lupa mengubur satu mayat lagi. Datuk mengeluarkan geraman yang berarti: “Berhenti ngomong, bau.” Dan, Nin, yang sudah terbiasa mengartikan geraman Datuk sejak bayi, menaikkan nada suaranya dan bilang: “Berikutnya dia yang kita kubur!” Sementara Nin sibuk menyumbangkan pendapatnya mengenai luas lubang yang diperlukan untuk mengubur Datuk (“Seluas Samarinda, minimal, untuk perutnya saja! He, Gendut, diet!”), aku memikirkan betapa tepatnya ucapan Nin (bukan soal luas kuburan Datuk).\n" +
                "\n" + "Hari ini, di pemakaman, ada orang yang dikubur, dan ada orang yang mengubur. Tapi, sepertinya, kematian mengambil keduanya—satu orang mati dan satu orang hidup. Bukan salah kematian, kurasa. Kematian hanya mengambil satu dari mereka. Masalahnya, yang ditinggal berusaha mengejar, berharap kematian mau mengembalikan apa yang dia ambil.", R.drawable.cover9, false));
        books.add(new Book("Rumah Kecil Alie", "Regita - Lenn Liu", "2025", "Pernahkah Anda terpikir betapa menariknya dunia yang terbuka lebar lewat lembaran buku? Membaca bukan hanya kegiatan rutin, tetapi juga petualangan tak terbatas ke dalam imajinasi dan pengetahuan. Membaca mengasah pikiran, membuka wawasan, dan memperkaya kosakata. Ini adalah pintu menuju dunia di luar kita yang tak terbatas. Tetapkan waktu khusus untuk membaca setiap hari.\n" +
                "\n" + "Dari membaca sebelum tidur hingga menyempatkan waktu di pagi hari, kebiasaan membaca dapat dibentuk dengan konsistensi. Pilih buku sesuai minat dan level literasi. Mulailah dengan buku yang sesuai dengan keinginan dan kemampuan membaca. Temukan tempat yang tenang dan nyaman untuk membaca. Lampu yang cukup, kursi yang nyaman, dan sedikit musik pelataran bisa menciptakan pengalaman membaca yang lebih baik. Bergabunglah dalam kelompok membaca atau forum literasi. Diskusikan buku yang Anda baca dan dapatkan rekomendasi dari sesama pembaca. Buat catatan atau jurnal tentang buku yang telah Anda baca.", R.drawable.cover10, false));
        books.add(new Book("Ranah Pusaka", "Nellaneva", "2025", "\"Ada benda yang kucari. Barang berharga. Sebuah pusaka. Sangat penting, tapi belum ketemu sampai sekarang. Aku ingin kalian bantu aku menemukannya,\" ungkap Arka, si pemilik kosan. Di dunia yang memaksa semua orang untuk serupa, yang Kali, Badran, dan Ilyas inginkan hanya bebas. Menggagas. Mengganas. Kemudian, lepas. Namun, permintaan Arka untuk mencari pusaka di dalam rumah indekosnya membuat mereka bertiga tidak bisa ‘bebas’ begitu saja. Demi iming-iming sewa kosan gratis, mereka pun bekerja sama untuk memecahkan teka-teki rangkaian pusaka yang tersembunyi di dalam rumah indekos sekaligus—secara tak terduga—menguak rahasia terbesar satu sama lain.", R.drawable.cover11, false));
        books.add(new Book("Untukmu, Anak Bungsu", "Hidya Hanin", "2025", "Sebagian besar orang beranggapan bahwa anak bungsu adalah anak yang paling disayang dan dimanja. Nyatanya, di balik itu semua, anak bungsu terkadang tidak punya kesempatan untuk menyuarakan suaranya sendiri. Dia harus mengikuti apa-apa yang sudah ditetapkan untuknya, tanpa dilihat keinginannya sendiri.\n" +
                "\n" + "Buku ini adalah suara-suara si anak bungsu yang keresahannya kadang tidak terlihat—disembunyikan. Si anak bungsu yang ingin memiliki suaranya sendiri. Si anak bungsu yang ingin menjadi harapan terakhir keluarga dengan caranya sendiri. Si anak bungsu yang memiliki cita-cita dan harapannya sendiri.", R.drawable.cover11, false));
        books.add(new Book("Funiculi Funicula", "Toshikazu Kawaguchi", "2021", "Kafe tua yang berada di gang kecil Tokyo terletak di bawah gedung lain, tidak butuh pendingin untuk mendinginkan Kafe tersebut. Tidak begitu ramai, namun terkenal karena bisa membawa pengunjungnya menjelajahi waktu. Keajaiban kafe itu menarik seorang wanita yang ingin memutar waktu untuk berbaikan dengan kekasihnya, seorang perawat yang ingin membaca surat yang tak sempat diberikan suaminya yang sakit, seorang kakak yang ingin menemui adiknya untuk terakhir kali, dan seorang ibu yang ingin bertemu dengan anak yang mungkin takkan pernah dikenalnya. Namun ada banyak peraturan yang harus diingat. Satu, mereka harus tetap duduk di kursi yang telah ditentukan. Dua, apapun yang mereka lakukan di masa yang didatangi takkan mengubah kenyataan di masa kini. Tiga, mereka harus menghabiskan kopi khusus yang disajikan sebelum kopi itu dingin. Rentetan peraturan lainnya tak menghentikan orang-orang itu untuk menjelajahi waktu. Akan tetapi, jika kepergian mereka tak mengubah satu hal pun di masa kini, layakkah semua itu dijalani?", R.drawable.cover12, false));
        books.add(new Book("The Orange Girl", "Jostein Gaarder", "2025", "Bagaimana perasaanmu jika mendapat surat seperti di atas dari ayahmu yang meninggal sebelas tahun lalu?\n" +
                "\n" + "Itulah yang dialami oleh Georg Røed pada usianya yang ke-15. Dia tak habis pikir mengapa ayahnya, di kala menjelang wafat, memutuskan untuk menuliskan kisah cintanya dengan seorang gadis misterius. Si Gadis Jeruk, demikian ayahnya menyebut gadis tersebut. Siapa sebenarnya si Gadis Jeruk itu? Dan mengapa pula ayahnya menanyakan kabar Teleskop Ruang Angkasa Hubble?", R.drawable.cover13, false));
        books.add(new Book("The Magic Library", "Jostein Gaarder", "2025", "Dua saudara sepupu, Berit dan Nils, tinggal di kota yang berbeda. Untuk berhubungan, kedua remaja ini membuat sebuah buku-surat yang mereka tulisi dan saling kirimkan di antara mereka. Anehnya, ada seorang wanita misterius, Bibbi Bokken, yang mengincar buku-surat itu. Bersama komplotannya, tampaknya Bibbi menjalankan sebuah rencana rahasia atas diri Berit dan Nils. Rencana itu berhubungan dengan sebuah perpustakaan ajaib dan konspirasi dunia perbukuan. Berit dan Nils tidak gentar, bahkan bertekad mengungkap misteri ini dan menemukan Perpustakaan Ajaib.", R.drawable.cover14, false));
        books.add(new Book("Solo Leveling 7", "DUBU/CHUGONG", "2025", "Tewasnya beberapa hunter level S yang terkemuka membuat seluruh dunia terguncang. Jin-woo tahu, para pelakunya pasti akan menyerang mereka kembali. Dengan terbentuknya gate luar biasa besar di atas langit kota Seoul, perang akan terjadi lebih cepat dari yang diperkirakan. Mampukah Jin-woo menyelamatkan semua orang dari bencana terbesar ini? Apakah sejarah umat manusia akan segera berakhir? Atau , justru ini akan menjadi awal babak baru?", R.drawable.cover15, false));
    }

    public static void removeFromFavorites(Book book) {
        favoriteBooks.remove(book);
        book.isLiked = false;
    }
}
